-- Rename DISTRICT_LEADER to DISTRICT_COORDINATOR
ALTER TYPE user_role RENAME VALUE 'DISTRICT_LEADER' TO 'DISTRICT_COORDINATOR';

-- Update default roles on profiles table
ALTER TABLE profiles ALTER COLUMN roles SET DEFAULT '{DISTRICT_COORDINATOR}';
